config/routes.rb
Tennis::Application.routes.draw do

  resources :performances

  match "performances/index/:id" => "performances#index", :as=>:performance_lesson, :via=>:get
  match "performances/new/:id" => "performances#new", :as=>:new_performance_lesson, :via=>:get

  
  resources :types

  devise_for :users

  resources :tournaments

  resources :disciplines

  resources :players

  resources :coaches

  resources :locations

  resources :lessons

  get "home/index"

   root :to => 'lessons#index'

end

app/models/lesson.rb
class Lesson < ActiveRecord::Base
  attr_accessible :coach_id, :date, :location_id, :notes, :type_id, :player_id, :points
  
  has_many :performances
  has_many :disciplines, :through=>:performances
  belongs_to :coach
  belongs_to :location
  belongs_to :player
  belongs_to :type
  
  validates_presence_of :coach_id
  validates_presence_of :player_id
  validates_presence_of :location_id
  

  default_scope order('date DESC')
  
  
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  # GET /lessons
  # GET /lessons.json
  def index
    @lessons = Lesson.where("player_id IN (?)",Player.find_all_by_user_id(current_user).collect{|a|a.id})
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @lessons }
    end
  end

  # GET /lessons/1
  # GET /lessons/1.json
  def show
    @lesson = Lesson.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @lesson }
    end
  end

  # GET /lessons/new
  # GET /lessons/new.json
  def new
    @lesson = Lesson.new
    
    @coaches=Coach.find_all_by_user_id(current_user.id)
    @players=Player.find_all_by_user_id(current_user.id)
    @locations=Location.find_all_by_user_id(current_user.id)
    @types=Type.find_all_by_user_id(current_user.id)
    
    

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @lesson }
    end
  end

  # GET /lessons/1/edit
  def edit
    @lesson = Lesson.find(params[:id])
    @coaches=Coach.find_all_by_user_id(current_user.id)
    @players=Player.find_all_by_user_id(current_user.id)
    @locations=Location.find_all_by_user_id(current_user.id)
    @types=Type.find_all_by_user_id(current_user.id)
    
  end

  # POST /lessons
  # POST /lessons.json
  def create
    @lesson = Lesson.new(params[:lesson])
    @coaches=Coach.find_all_by_user_id(current_user.id)
    @players=Player.find_all_by_user_id(current_user.id)
    @locations=Location.find_all_by_user_id(current_user.id)
    @types=Type.find_all_by_user_id(current_user.id)
    
    respond_to do |format|
      if @lesson.save
        format.html { redirect_to lessons_path, notice: 'Lesson was successfully created.' }
        format.json { render json: @lesson, status: :created, location: @lesson }
      else
        format.html { render action: "new" }
        format.json { render json: @lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /lessons/1
  # PUT /lessons/1.json
  def update
    @lesson = Lesson.find(params[:id])

    respond_to do |format|
      if @lesson.update_attributes(params[:lesson])
        format.html { redirect_to lessons_path, notice: 'Lesson was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lessons/1
  # DELETE /lessons/1.json
  def destroy
    @lesson = Lesson.find(params[:id])
    @lesson.destroy

    respond_to do |format|
      format.html { redirect_to lessons_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/views/lessons/_form.html.erb
<%content_for :js do%>

<script type="text/javascript">
  $(function() {
    $('#datetimepicker1').datetimepicker({
      	language: 'en',
		pickSeconds: false         // disables seconds in the time picker
    });

	<% if !@lesson.date.blank? %>

	var picker = $('#datetimepicker1').data('datetimepicker');
    picker.setDate(new Date(Date.UTC(<%="#{@lesson.date.year},#{@lesson.date.month-1},#{@lesson.date.day},#{@lesson.date.hour},#{@lesson.date.min}"%>)));
	
	<% end %>

  });
</script>

<%end%>

<%= form_for @lesson, :html => { :class => 'form-horizontal' } do |f| %>
<% if @lesson.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@lesson.errors.count, "error") %> prohibited this lesson from being saved:</h2>

    <ul>
    <% @lesson.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>



  <!-- <div class="control-group">
    <%#= f.label :date, :class => 'control-label' %>
    <div class="controls">
      <%#= f.datetime_select :date, :class => 'datetime_select' %>
    </div>
  </div> -->


  <div class="control-group">
   <%= f.label :date, :class => 'control-label' %>
 	<div class="controls">
  <div id="datetimepicker1" class="input-append date">
	<%= f.text_field :date, "data-format"=>"dd/MM/yyyy hh:mm", :class=>'date-time-input text_field' %>
    <span class="add-on">
      <i data-time-icon="icon-time" data-date-icon="icon-calendar">
      </i>
    </span>
  </div>
  </div>
</div>

  <div class="control-group">
   <%= f.label :player_id, :class => 'control-label' %>

     <div class="controls">
		<%=f.select :player_id, options_for_select(@players.collect{|c| ["#{c.first_name} #{c.last_name}", c.id]}, @lesson.player_id), :prompt=>"Choose Player" %>	
    </div>
  </div>
  <div class="control-group">
    <%= f.label :coach_id, :class => 'control-label' %>
    <div class="controls">

	<%=f.select :coach_id, options_for_select(@coaches.collect{|c| [c.name, c.id]}, @lesson.coach_id), :prompt=>"Choose Coach" %>	
     </div>
  </div>
  <div class="control-group">
    <%= f.label :location_id, :class => 'control-label' %>
    <div class="controls">
		<%=f.select :location_id, options_for_select(@locations.collect{|c| [c.name, c.id]}, @lesson.location_id), :prompt=>"Choose Location" %>	
    </div>
  </div>
  <div class="control-group">
    <%= f.label :type_id, :class => 'control-label' %>
    <div class="controls">
		<%=f.select :type_id, options_for_select(@types.collect{|c| [c.name, c.id]}, @lesson.type_id), :prompt=>"Choose Lesson Type" %>	
    </div>
  </div>

  <div class="control-group">
    <%= f.label :points, :class => 'control-label' %>
    <div class="controls">
		<%=f.select :points, options_for_select(0..10, @lesson.points), :prompt=>"Choose Points" %>	
    </div>
  </div>

  <div class="control-group">
    <%= f.label :notes, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :notes, :class => 'text_area',  :rows=>"3" %>
    </div>
  </div>


  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-success' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                lessons_path, :class => 'btn' %>
  </div>
<% end %>

app/views/lessons/index.html.erb
<%- model_class = Lesson -%>

<div class="row-fluid">
  <div class="span12 content">

<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:player) %></th>
      <th><%= model_class.human_attribute_name(:day) %></th>
      <th><%= model_class.human_attribute_name(:time) %></th>
      <th class="hidden-phone hidden-tablet"><%= model_class.human_attribute_name(:coach_id) %></th>
      <th class="hidden-phone hidden-tablet"><%= model_class.human_attribute_name(:location_id) %></th>
      <th><%= model_class.human_attribute_name(:performance) %></th>
      <th class="hidden-phone hidden-tablet"><%= model_class.human_attribute_name(:points) %></th>
      <th class="hidden-phone hidden-tablet"><%= model_class.human_attribute_name(:notes) %></th>
      <th class="hidden-phone hidden-tablet"><%= model_class.human_attribute_name(:type) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @lessons.each do |lesson| %>
      <tr>
        <td><%= lesson.player.first_name %> <%= lesson.player.last_name %></td>
        <td><%= lesson.date.strftime("%d %b %Y ") %></td>
        <td><%= lesson.date.strftime("%H:%M") %></td>
        <td class="hidden-phone hidden-tablet"><%= lesson.coach.name %></td>
        <td class="hidden-phone hidden-tablet"><%= lesson.location.name %></td>
        <td>
				<%if !lesson.performances.blank?%>
			<table class="table table-striped table-bordered discipline-table">
			  <tbody>
			    <% lesson.performances.each do |performance| %>
			      <tr>
			        <td><%= performance.discipline.name%></td>
			        <td><%= performance.points%></td>
			        <td><%= performance.notes%></td>
			      </tr>
			    <% end %>
			  </tbody>
			</table>
			<%end%>
<%= link_to "Manage Performance", performance_lesson_path(lesson.id), :class=>"btn  btn-mini btn-success"%>
		</td>
        <td class="hidden-phone hidden-tablet"><%= lesson.points==0 ? "None" : lesson.points %></td>
        <td class="hidden-phone hidden-tablet"><%= lesson.notes %></td>
        <td class="hidden-phone hidden-tablet"><%= lesson.type.name %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_lesson_path(lesson), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      lesson_path(lesson),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_lesson_path,
            :class => 'btn btn-success' %>

				</div>
		</div>

app/views/lessons/show.html.erb
<%- model_class = Lesson -%>
<div class="row-fluid">
  	<div class="span12 content">

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:date) %>:</strong></dt>
  <dd><%= @lesson.date %></dd>
  <dt><strong><%= model_class.human_attribute_name(:coach_id) %>:</strong></dt>
  <dd><%= @lesson.coach_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:notes) %>:</strong></dt>
  <dd><%= @lesson.notes %></dd>
  <dt><strong><%= model_class.human_attribute_name(:location_id) %>:</strong></dt>
  <dd><%= @lesson.location_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:private) %>:</strong></dt>
  <dd><%= @lesson.private %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              lessons_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_lesson_path(@lesson), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              lesson_path(@lesson),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

	</div>
</div>