config/routes.rb
Tennis::Application.routes.draw do

  resources :performances

  match "performances/index/:id" => "performances#index", :as=>:performance_lesson, :via=>:get
  match "performances/new/:id" => "performances#new", :as=>:new_performance_lesson, :via=>:get

  
  resources :types

  devise_for :users

  resources :tournaments

  resources :disciplines

  resources :players

  resources :coaches

  resources :locations

  resources :lessons

  get "home/index"

   root :to => 'lessons#index'

end

app/models/coach.rb
class Coach < ActiveRecord::Base
  attr_accessible :name
  
    has_many :lessons
    
    validates_presence_of :name
    
    
end

app/models/discipline.rb
class Discipline < ActiveRecord::Base
  attr_accessible :name
  
  has_many :performances
  has_many :lessons, :through=>:performances
  
      validates_presence_of :name
end

app/models/lesson.rb
class Lesson < ActiveRecord::Base
  attr_accessible :coach_id, :date, :location_id, :notes, :type_id, :player_id, :points
  
  has_many :performances
  has_many :disciplines, :through=>:performances
  belongs_to :coach
  belongs_to :location
  belongs_to :player
  belongs_to :type
  
  validates_presence_of :coach_id
  validates_presence_of :player_id
  validates_presence_of :location_id
  

  default_scope order('date DESC')
  
  
end

app/models/location.rb
class Location < ActiveRecord::Base
  attr_accessible :name
  
    has_many :lessons
    
        validates_presence_of :name
end

app/models/performance.rb
class Performance < ActiveRecord::Base
  attr_accessible :discipline_id, :lesson_id, :notes, :points
  
  
  belongs_to :discipline
  belongs_to :lesson
  
  validates_presence_of :discipline_id
  validates_presence_of :points
    
  validates_uniqueness_of :discipline_id, :scope => [:lesson_id]

end

app/models/player.rb
class Player < ActiveRecord::Base
  attr_accessible :first_name, :last_name, :user_id
  
  has_many :lessons
  has_many :tournaments
  belongs_to :user
  
  validates_presence_of :first_name
  validates_presence_of :last_name
  validates_presence_of :user_id
  
  end

app/models/tournament.rb
class Tournament < ActiveRecord::Base
  attr_accessible :date, :name, :notes, :player_id, :result
  
  
  belongs_to :player
  
      validates_presence_of :name
      validates_presence_of :player_id
          validates_presence_of :date    
  
end

app/models/type.rb
class Type < ActiveRecord::Base
  attr_accessible :name
  
  has_many :lessons
  
  validates_presence_of :name
  end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :first_name, :last_name
  # attr_accessible :title, :body
  
  has_many :players
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/coaches_helper.rb
module CoachesHelper
end

app/helpers/disciplines_helper.rb
module DisciplinesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/performances_helper.rb
module PerformancesHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/tournaments_helper.rb
module TournamentsHelper
end

app/helpers/types_helper.rb
module TypesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Tennis Monitor" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'ball-144.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'ball-114.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'ball-72.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'ball-57.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
  </head>
  <body>

    <div class="navbar navbar-fluid-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
         <a class="brand" href="/"><%=image_tag "ball.png"%> Tennis Monitor</a>
          <div class="container-fluid nav-collapse">
            <ul class="nav top20">

			<%if current_user%>
	              <li><%= link_to "Lessons", lessons_path  %></li>
	              <li><%= link_to "Tournaments", tournaments_path  %></li>
              <li class="dropdown">
			    <a class="dropdown-toggle"
			       data-toggle="dropdown"
			       href="#">
			        Settings
			        <b class="caret"></b>
			      </a>
			    <ul class="dropdown-menu">
	              <li><%= link_to "Coaches", coaches_path  %></li>
	              <li><%= link_to "Location", locations_path  %></li>
	              <li><%= link_to "Player", players_path  %></li>
	              <%if current_user.id==1%><li><%= link_to "Disciplines", disciplines_path  %></li><%end%>
	              <li><%= link_to "Lesson Types", types_path  %></li>
			    </ul>
			  </li>
              <li><%= link_to "Account", edit_user_registration_path  %></li>
			  <li><%=link_to "Logout", destroy_user_session_path, :method=>:delete	%></li>
			<%end%>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row-fluid">

        <div class="span12">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <p>&copy; Clive Baker</p>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>
          <%= yield :js %>
  </body>
</html>